# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmaugUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrcUserHost',
            fields=[
                ('host', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(db_index=True)),
                ('proto', models.CharField(choices=[('irc', 'IRC'), ('discord', 'Discord')], db_index=True, max_length=8)),
                ('handle', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('month', models.IntegerField(blank=True, db_index=True, null=True)),
                ('external_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('edited', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], db_index=True, max_length=1, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('passed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('seen', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('stamp', models.DateTimeField(db_index=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('match_text', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RpsGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_play', models.CharField(blank=True, max_length=3)),
                ('winner_time', models.CharField(blank=True, max_length=16)),
                ('loser_play', models.CharField(blank=True, max_length=3)),
                ('loser_time', models.CharField(blank=True, max_length=16)),
                ('rounds', models.IntegerField(blank=True, null=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rps_losses', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rps_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmaugUserHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(db_index=True, max_length=64)),
                ('proto', models.CharField(choices=[('irc', 'IRC'), ('discord', 'Discord')], db_index=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SmaugUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto', models.CharField(choices=[('irc', 'IRC'), ('discord', 'Discord')], db_index=True, max_length=8)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('darkblue', 'Dark Blue'), ('green', 'Green'), ('red', 'Red'), ('maroon', 'Dark Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('teal', 'Teal'), ('aqua', 'Aquamarine'), ('blue', 'Blue'), ('fuchsia', 'Fuchsia'), ('gray', 'Gray'), ('silver', 'Silver')], max_length=16, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_on', models.DateTimeField(blank=True, null=True)),
                ('sign_off', models.DateTimeField(blank=True, null=True)),
                ('last_comment', models.DateTimeField(blank=True, null=True)),
                ('access', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_logs', 'Can view logs'),),
            },
        ),
        migrations.AddField(
            model_name='smauguserhandle',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='ircview.SmaugUserProfile'),
        ),
        migrations.AddField(
            model_name='ircuserhost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='ircview.SmaugUserProfile'),
        ),
        migrations.AlterIndexTogether(
            name='logline',
            index_together=set([('year', 'month')]),
        ),
    ]
